<template>
  <v-dialog v-model="dialog" :disabled="disabled" content-class="uiPopup" width="400px" max-width="100vw" persistent @keydown.esc="dialog = false">
    <a slot="activator" href="javascript:void(0);" @click="dialog = true">Reset wallet password</a>
    <v-card class="elevation-12">
      <div class="popupHeader ClearFix">
        <a class="uiIconClose pull-right" aria-hidden="true" @click="dialog = false"></a>
        <span class="PopupTitle popupTitle">Reset wallet</span>
      </div>
      <v-card-text>
        <div v-if="errorMessage" class="alert alert-error">
          <i class="uiIconError"></i>
          {{ errorMessage }}
        </div>

        <div v-if="rememberPassword" class="alert alert-warning v-content">
          <i class="uiIconWarning"></i>
          You have chosen to remember your password, thus your password will be stored in current browser and you will not have to re-enter it again to unlock your wallet.
        </div>
        <div v-else class="alert alert-info v-content">
          <i class="uiIconInfo"></i>
          You have chosen to not remember your password, thus you will have to unlock your wallet each time you want to make a transaction with your wallet.
        </div>
    
        <v-text-field
          v-if="!autoGeneratedPassword"
          v-model="walletPassword"
          :append-icon="walletPasswordShow ? 'visibility_off' : 'visibility'"
          :rules="[rules.min]"
          :type="walletPasswordShow ? 'text' : 'password'"
          name="walletPassword"
          label="Current wallet password"
          counter
          @click:append="walletPasswordShow = !walletPasswordShow"
        />
    
        <v-text-field
          v-model="newWalletPassword"
          :append-icon="newWalletPasswordShow ? 'visibility_off' : 'visibility'"
          :rules="[rules.min]"
          :type="newWalletPasswordShow ? 'text' : 'password'"
          name="newWalletPassword"
          label="New wallet password"
          counter
          @click:append="newWalletPasswordShow = !newWalletPasswordShow"
        />
    
        <v-switch v-model="rememberPassword" label="Remember my password" />
      </v-card-text>
      <v-card-actions>
        <v-spacer />
        <button class="btn btn-primary mr-1" @click="resetWallet">Reset</button>
        <button class="btn" @click="dialog = false">Close</button>
        <v-spacer />
      </v-card-actions>
    </v-card>
  </v-dialog>
</template>

<script>
import {unlockWallet, saveWallet, removeWallet} from '../WalletUtils.js';

export default {
  data() {
    return {
      dialog: false,
      errorMessage: null,
      walletPassword: '',
      walletPasswordShow: false,
      newWalletPassword: '',
      newWalletPasswordShow: false,
      autoGeneratedPassword: false,
      browserWalletDecrypted: false,
      rememberPassword: false,
      rules: {
        min: v => v.length >= 8 || 'At least 8 characters'
      }
    };
  },
  watch: {
    dialog() {
      if (this.dialog) {
        this.errorMessage = null;
        this.walletPassword = '';
        this.walletPasswordShow = false;
        this.newWalletPassword = '';
        this.newWalletPasswordShow = false;
        this.rememberPassword = false;
        this.autoGeneratedPassword = window.walletSettings.userPreferences.autoGenerated;
        this.browserWalletDecrypted = window.walletSettings.browserWallet;
        if (!this.browserWalletDecrypted && this.autoGeneratedPassword) {
          this.errorMessage = 'Can\'t reset wallet because it\'s encrypted';
        }
      }
    }
  },
  methods: {
    resetWallet() {
      const unlocked = this.autoGeneratedPassword || unlockWallet(this.walletPassword, true);
      if (unlocked) {
        try {
          saveWallet(this.newWalletPassword);
        } catch (e) {
          console.debug("saveWallet method error", e);
          this.errorMessage = String(e);
          return;
        }
        if (unlockWallet(this.newWalletPassword, true, this.rememberPassword)) {
          this.dialog = false;
        } else {
          this.errorMessage = 'An error occurred while resetting wallet password';
          return;
        }
      } else {
        this.errorMessage = 'Wrong password';
      }
    }
  }
};
</script>