<template>
  <v-dialog
    v-model="dialog"
    content-class="uiPopup with-overflow not-draggable"
    width="400px"
    max-width="100vw"
    @keydown.esc="dialog = false">
    <a
      slot="activator"
      href="javascript:void(0);"
      @click="dialog = true">
      Backup on server
    </a>
    <v-card class="elevation-12">
      <div class="popupHeader ClearFix">
        <a
          class="uiIconClose pull-right"
          aria-hidden="true"
          @click="dialog = false"></a>
        <span class="PopupTitle popupTitle">
          Save wallet private key on server
        </span>
      </div>
      <v-card-text class="text-xs-center">
        <div v-if="error && !loading" class="alert alert-error">
          <i class="uiIconError"></i>{{ error }}
        </div>
        <v-form ref="form">
          <div class="alert alert-info">
            <i class="uiIconInfo"></i>
            You are about saving your private key encryped on server side.
            Only you will be able to get your private key on other devices using the following password that you will enter.
          </div>
          <v-text-field
            v-if="dialog && !autoGeneratedPassword"
            v-model="walletPassword"
            :append-icon="walletPasswordShow ? 'visibility_off' : 'visibility'"
            :rules="[rules.min]"
            :type="walletPasswordShow ? 'text' : 'password'"
            :disabled="loading"
            name="walletPassword"
            label="Current wallet password"
            placeholder="Enter your wallet password"
            autocomplete="current-passord"
            counter
            autofocus
            required
            @click:append="walletPasswordShow = !walletPasswordShow" />
          <v-text-field
            v-if="dialog"
            v-model="newWalletPassword"
            :append-icon="newWalletPasswordShow ? 'visibility_off' : 'visibility'"
            :rules="[rules.min]"
            :type="newWalletPasswordShow ? 'text' : 'password'"
            :disabled="loading"
            name="newWalletPassword"
            label="New wallet password"
            placeholder="Enter new wallet password"
            autocomplete="new-passord"
            counter
            required
            @click:append="newWalletPasswordShow = !newWalletPasswordShow" />
        </v-form>
      </v-card-text>
      <v-card-actions>
        <v-spacer />
        <v-btn
          :disabled="loading"
          :loading="loading"
          class="btn btn-primary mr-1"
          @click="sendPrivateKey">
          Save
        </v-btn>
        <button
          :disabled="loading"
          class="btn"
          color="secondary"
          @click="dialog = false">
          Close
        </button>
        <v-spacer />
      </v-card-actions>
    </v-card>
  </v-dialog>
</template>

<script>
import {sendPrivateKey} from '../WalletUtils.js';

export default {
  props: {
    walletAddress: {
      type: String,
      default: function() {
        return null;
      },
    },
  },
  data() {
    return {
      dialog: false,
      walletPassword: null,
      walletPasswordShow: false,
      newWalletPassword: null,
      newWalletPasswordShow: false,
      autoGeneratedPassword: false,
      loading: false,
      error: null,
      rules: {
        min: (v) => (v && v.length >= 8) || 'At least 8 characters',
      },
    };
  },
  watch: {
    dialog() {
      if (this.dialog) {
        this.autoGeneratedPassword = window.walletSettings.userPreferences.autoGenerated;
        this.walletPassword = null;
        this.walletPasswordShow = false;
        this.newWalletPassword = null;
        this.newWalletPasswordShow = false;
        this.loading = false;
        this.error = null;
        this.$refs.form.reset();
      }
    },
  },
  methods: {
    sendPrivateKey() {
      this.error = null;

      if(!this.$refs.form.validate()) {
        return false;
      }

      this.loading = true;
      return sendPrivateKey(this.walletAddress, this.walletPassword, this.newWalletPassword)
        .then((result, error) => {
          if (error) {
            console.log("error", error);
            throw error;
          }
          window.walletSettings.userPreferences.hasKeyOnServerSide = true;
          this.$emit('saved');
          this.dialog = false;
        })
        .catch(e => {
          console.debug('Error saving private key on server', e);
          this.error = String(e)
        })
        .finally(() => {
          this.loading = false;
        });
    },
  },
}
</script>