<template>
  <v-dialog v-model="dialog" :disabled="disabled" class="fixLinkHeight" content-class="uiPopup" width="500px" max-width="100vw" persistent @keydown.esc="dialog = false">
    <a slot="activator" href="javascript:void(0);" @click="dialog = true">Backup your wallet</a>
    <v-card class="elevation-12">
      <div class="popupHeader ClearFix">
        <a class="uiIconClose pull-right" aria-hidden="true" @click="dialog = false"></a>
        <span class="PopupTitle popupTitle">Backup wallet</span>
      </div>
      <v-card-text>
        <div v-if="errorMessage" class="alert alert-error">
          <i class="uiIconError"></i>
          {{ errorMessage }}
        </div>

        <div v-if="displayCompleteMessage" class="alert alert-warning v-content">
          <p>
            <i class="uiIconWarning"></i>
            Currently your wallet is accessible only on this browser and only on this machine.
            <br/>
            You should copy the following private key to be able to:
            <br/>
            - restore your wallet in other devices/browsers
            <br/>
            - and/or restore your wallet in case you can't access your browser anymore (OS recovery, machine disk formatted, browser uninstalled ...)
          </p>
          <p>
            Please make sure to keep your wallet in a safe place where nobody else can get it (Write it in a piece of paper and hide it for example).
            <br/>
            If the following code is hacked by someone, <strong>he will be able to own all your funds</strong>.
          </p>
        </div>
        <div v-else class="alert alert-warning v-content">
          <p>
            <i class="uiIconWarning"></i>
            Please make sure to keep your wallet in a safe place where nobody else can get it (Write it in a piece of paper and hide it for example).
            <br/>
            If the following code is hacked by someone, <strong>he will be able to own all your funds</strong>.
          </p>
        </div>

        <v-form>
          <v-text-field
            v-if="!autoGeneratedPassword && !walletPrivateKey"
            v-model="walletPassword"
            :append-icon="walletPasswordShow ? 'visibility_off' : 'visibility'"
            :rules="[rules.min]"
            :type="walletPasswordShow ? 'text' : 'current-password'"
            name="walletPassword"
            label="Current wallet password"
            placeholder="Input your current wallet password"
            counter
            @click:append="walletPasswordShow = !walletPasswordShow"
          />
        </v-form>
      </v-card-text>
      <v-card-text class="text-xs-center">
        <wallet-address v-if="walletPrivateKey" id="walletPrivateKey" :value="walletPrivateKey" :allow-copy="false" />
      </v-card-text>
      <v-card-actions>
        <v-spacer />
        <button v-if="walletPrivateKey" class="btn btn-primary mr-1" @click="backedUp">Backed up!</button>
        <button v-if="!walletPrivateKey" class="btn btn-primary mr-1" @click="showPrivateKey">Display</button>
        <button v-if="!walletPrivateKey" class="btn" @click="dialog = false">Close</button>
        <v-spacer />
      </v-card-actions>
    </v-card>
  </v-dialog>
</template>

<script>
import WalletAddress from './WalletAddress.vue';

import {unlockBrowerWallet, getCurrentBrowerWallet, setWalletBackedUp} from '../WalletUtils.js';

export default {
  components: {
    WalletAddress
  },
  props: {
    displayCompleteMessage: {
      type: Boolean,
      default: function() {
        return false;
      }
    }
  },
  data() {
    return {
      dialog: false,
      errorMessage: null,
      walletPassword: '',
      walletPasswordShow: false,
      walletPrivateKey: null,
      autoGeneratedPassword: false,
      browserWalletDecrypted: false,
      rules: {
        min: v => v.length >= 8 || 'At least 8 characters'
      }
    };
  },
  watch: {
    dialog() {
      if (this.dialog) {
        this.errorMessage = null;
        this.walletPrivateKey = null;
        this.walletPassword = '';
        this.walletPasswordShow = false;
        this.autoGeneratedPassword = window.walletSettings.userPreferences.autoGenerated;
        this.browserWalletDecrypted = window.walletSettings.browserWallet;
      }
    }
  },
  methods: {
    backedUp() {
      setWalletBackedUp(null, true);
      this.$emit("copied");
      this.dialog = false;
    },
    showPrivateKey() {
      const unlocked = this.autoGeneratedPassword || unlockBrowerWallet(this.walletPassword, null, null, true, false);
      if (unlocked) {
        const wallet = getCurrentBrowerWallet();
        if (!wallet || !wallet.privateKey) {
          this.errorMessage = 'Can\'t find your wallet in current browser';
          return;
        }
        this.walletPrivateKey = wallet.privateKey;
      } else {
        this.errorMessage = 'Wrong password';
      }
    }
  }
};
</script>