<template>
  <v-dialog v-model="dialog" :disabled="disabled" content-class="uiPopup" width="500px" max-width="100vw" persistent @keydown.esc="dialog = false">
    <a slot="activator" href="javascript:void(0);" @click="dialog = true">{{ buttonLabel }}</a>
    <v-card class="elevation-12">
      <div class="popupHeader ClearFix">
        <a class="uiIconClose pull-right" aria-hidden="true" @click="dialog = false"></a>
        <span class="PopupTitle popupTitle">Reset wallet password</span>
      </div>
      <v-card-title v-show="loading" class="pb-0">
        <v-spacer />
        <v-progress-circular color="primary" indeterminate size="20"></v-progress-circular>
        <v-spacer />
      </v-card-title>
      <v-card-text>
        <div v-if="errorMessage" class="alert alert-error">
          <i class="uiIconError"></i>
          {{ errorMessage }}
        </div>

        <div v-if="rememberPassword" class="alert alert-warning v-content">
          <i class="uiIconWarning"></i>
          You have chosen to remember your password, thus your password will be stored in current browser and you will not have to re-enter it again to unlock your wallet.
        </div>
        <div v-else class="alert alert-info v-content">
          <i class="uiIconInfo"></i>
          You have chosen to not remember your password, thus you will have to unlock your wallet each time you want to make a transaction with your wallet.
        </div>

        <v-form>
          <v-text-field
            v-if="!autoGeneratedPassword"
            v-model="walletPassword"
            :append-icon="walletPasswordShow ? 'visibility_off' : 'visibility'"
            :rules="[rules.min]"
            :type="walletPasswordShow ? 'text' : 'password'"
            :disabled="loading"
            name="walletPassword"
            label="Current wallet password"
            placeholder="Input your current wallet password"
            counter
            @click:append="walletPasswordShow = !walletPasswordShow"
          />
      
          <v-text-field
            v-model="newWalletPassword"
            :append-icon="newWalletPasswordShow ? 'visibility_off' : 'visibility'"
            :rules="[rules.min]"
            :type="newWalletPasswordShow ? 'text' : 'password'"
            :disabled="loading"
            name="newWalletPassword"
            label="New wallet password"
            placeholder="Input your new wallet password"
            counter
            @click:append="newWalletPasswordShow = !newWalletPasswordShow"
          />
      
          <v-switch v-model="rememberPassword" label="Remember my password" />
        </v-form>
      </v-card-text>
      <v-card-actions>
        <v-spacer />
        <button :disabled="loading" class="btn btn-primary mr-1" @click="resetWallet">Confirm</button>
        <button :disabled="loading" class="btn" @click="dialog = false">Close</button>
        <v-spacer />
      </v-card-actions>
    </v-card>
  </v-dialog>
</template>

<script>
import {unlockBrowerWallet, saveBrowerWallet, hashCode} from '../WalletUtils.js';

export default {
  props: {
    buttonLabel: {
      type: String,
      default: function() {
        return null;
      }
    }
  },
  data() {
    return {
      dialog: false,
      loading: false,
      errorMessage: null,
      walletPassword: '',
      walletPasswordShow: false,
      newWalletPassword: '',
      newWalletPasswordShow: false,
      autoGeneratedPassword: false,
      browserWalletDecrypted: false,
      rememberPassword: false,
      rules: {
        min: v => v.length >= 8 || 'At least 8 characters'
      }
    };
  },
  watch: {
    dialog() {
      if (this.dialog) {
        this.loading = false;
        this.errorMessage = null;
        this.walletPassword = '';
        this.walletPasswordShow = false;
        this.newWalletPassword = '';
        this.newWalletPasswordShow = false;
        this.rememberPassword = false;
        this.autoGeneratedPassword = window.walletSettings.userPreferences.autoGenerated;
        if (!window.walletSettings.browserWalletExists) {
          this.errorMessage = 'Can\'t reset wallet because it doesn\'t exist in current browser';
        }
      }
    }
  },
  methods: {
    resetWallet() {
      this.loading = true;
      // Check if original password is ok
      const unlocked = unlockBrowerWallet(this.autoGeneratedPassword ? window.walletSettings.userP : hashCode(this.walletPassword));
      if (unlocked) {
        try {
          saveBrowerWallet(this.newWalletPassword, null, null, false, this.rememberPassword);
          this.$emit("reseted");
          this.loading = false;
          this.dialog = false;
        } catch (e) {
          this.loading = false;
          console.debug("saveWallet method error", e);
          this.errorMessage = String(e);
          return;
        }
      } else {
        this.loading = false;
        this.errorMessage = 'Wrong password';
      }
    }
  }
};
</script>